services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio12345
      AWS_DEFAULT_REGION: us-east-1
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ENDPOINT_URL: http://minio:9000
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --artifacts-destination s3://mlflow-artifacts
      --serve-artifacts
    ports:
      - "5000:5000"
    depends_on:
      - minio

  zenml-server:
    image: zenmldocker/zenml-server:latest
    container_name: zenml-server
    ports:
      - "8080:8080"
    environment:
      ZENML_STORE_URL: sqlite:////zenml/zenml.db
      ZENML_SERVER_AUTH_DISABLED: "true"
    volumes:
      - zenml-data:/zenml
    depends_on:
      - mlflow

  training:
    container_name: training
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - zenml-client:/root/.config/zenml
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio12345
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT_URL: http://minio:9000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    depends_on:
      - minio
      - mlflow
      - zenml-server
    command: tail -f /dev/null

  api:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/app/api
    depends_on:
      - mlflow
    restart: always

volumes:
  miniodata:
  zenml-data:
  zenml-client:
